### ISSUE TITLE
Migrate relevant issues

### ISSUE THREAD

**Issue by kenan-rhoton** [doner-kebard/card-game#1]
We need to check which issues are relevant regarding rules and documentation from https://github.com/kenan-rhoton/card-game and migrate them here.

**Comment by Masclins** [comment]
I think they are already migrated. My only doubt is this one: https://github.com/kenan-rhoton/card-game/issues/120

@kenan-rhoton I leave it to you to either finish or close this Issue.

Also there's one that I'm not sure where it should go: https://github.com/kenan-rhoton/card-game/issues/124

**Comment by kenan-rhoton** [comment]
both of those are relevant to backend and frontend, (although the first one is already done for the backend)

**Comment by Masclins** [comment]
Second one had been copied to backend. Both will be migrated to frontend.

No issues are left to migrate to this project.
